lo:
  api-key: d2bf5cf323894b4bae08beac9cc4276e
  device-url: https://liveobjects.orange-business.com/api/v1/deviceMgt/devices
  
  uri: ssl://liveobjects.orange-business.com:8883
  username: connector
  
  topic: YOUR_TOPIC
  clientId: mqtt2iot
  recovery-interval: 10000
  completion-timeout: 20000
  connection-timeout: 30000
  qos: 1
  keep-alive-interval-seconds: 0
  
azure:
  iot-connection-string: YOUR_IOT_CONNECTION_STRING
  iot-host-name: YOUR_IOT_HOST_NAME
  synchronization-device-interval: 10000
  synchronization-thread-pool-size: 40
  messaging-thread-pool-size: 40
  device-client-connection-timeout: 5000
  tagPlatformKey: platform
  tagPlatformValue: LiveObjects
  application-insights:
    instrumentation-key: YOUR_INSTMENTATION_KEY
    channel:
      in-process:
        developer-mode: true
        max-telemetry-buffer-capacity: 500
        flush-interval-in-seconds: 5

flexibleengine:
  dis-endpoint: https://dis.eu-west-0.prod-cloud-ocb.orange-business.com
  dis-ak: WOYP9KUMUJT6BVSGZFRA
  dis-sk: Wqt5TbUxemsJ58nMZYxGHacmuQnOyRhwCPaNofY4
  dis-projectid: cddffdf04cf441c8b94aac85dfdc2a69
  dis-region: eu-west-0
  dis-StreamName: nhe-live-object
  synchronization-thread-pool-size: 40
  synchronization-device-interval: 10000
spring:
  application:
    name: Lo2IotHub
    